# Generated by Django 4.1.7 on 2023-06-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_student_id_alter_student_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='no', max_length=264),
            preserve_default=False,
        ),
    ]
