# Generated by Django 4.1.7 on 2023-06-05 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=264, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=264)),
                ('course_description', models.CharField(max_length=264)),
            ],
        ),
    ]
